import { Product, PluginSettings, OperationLog } from './types';

export const sampleBrandsList = [
  'Casio',
  'Seiko',
  'G-Shock',
  'TISSOT',
  'Swatch',
  'Calvin Klein',
  'Caterpillar',
  'CERRUTI',
  'Colbert',
  'Cover',
  'Daniel Gorman',
  'David Guner',
  'Edifice',
  'Esprit',
  'GUCCI',
  'Guess',
  'Ice',
  'Jowissa',
  'Orient',
  'POLICE',
  'Pro Trek',
  'Timberland',
  'Timex',
  'سامسونگ',
  'اپل',
  'شیائومی',
  'باسئوس'
];

export const samplePriceRangesList = [
  '۲ تا ۵ میلیون',
  '۵ تا ۱۰ میلیون',
  '۱۰ تا ۱۵ میلیون',
  '۱۵ تا ۲۰ میلیون',
  '۲۰ تا ۳۰ میلیون',
  '۳۰ تا ۴۰ میلیون',
  '۴۰ تا ۶۰ میلیون',
  '۶۰ تا ۷۰ میلیون',
  '۷۰ میلیون به بالا'
];

export const initialProducts: Product[] = [
  {
    id: 101,
    name: 'گوشی موبایل سامسونگ Galaxy S24 Ultra',
    sku: 'SAM-S24U-512',
    type: 'variable',
    status: 'publish',
    category: 'گوشی موبایل',
    brand: 'سامسونگ',
    priceRange: '۷۰ میلیون به بالا',
    attributes: { 'pa_brands': 'سامسونگ', 'pa_price-range': '۷۰ میلیون به بالا' },
    thumbnail: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=120&auto=format&fit=crop&q=60',
    description: 'گوشی پرچمدار سامسونگ با قلم S Pen، پردازنده Snapdragon 8 Gen 3 و دوربین ۲۰۰ مگاپیکسلی با هوش مصنوعی Galaxy AI.',
    shortDescription: 'پرچمدار ۲۰۲۴ سامسونگ با فریم تیتانیومی و دوربین ۲۰۰ مگاپیکسل',
    regularPrice: 78500000,
    salePrice: 76900000,
    manageStock: true,
    stockQuantity: 14,
    stockStatus: 'instock',
    snappayEnabled: true,
    torobPayEnabled: true,
    isPurchasable: true,
    variations: [
      {
        id: 1011,
        parentId: 101,
        sku: 'SAM-S24U-GRY',
        name: 'رنگ خاکستری تیتانیوم - 512GB',
        attributes: { 'رنگ': 'خاکستری تیتانیوم', 'حافظه': '512 گیگابایت' },
        regularPrice: 78500000,
        salePrice: 76900000,
        manageStock: true,
        stockQuantity: 8,
        stockStatus: 'instock',
        snappayEnabled: true,
        torobPayEnabled: true,
        isPurchasable: true
      },
      {
        id: 1012,
        parentId: 101,
        sku: 'SAM-S24U-BLK',
        name: 'رنگ مشکی تیتانیوم - 512GB',
        attributes: { 'رنگ': 'مشکی تیتانیوم', 'حافظه': '512 گیگابایت' },
        regularPrice: 79000000,
        salePrice: null,
        manageStock: true,
        stockQuantity: 6,
        stockStatus: 'instock',
        snappayEnabled: true,
        torobPayEnabled: false,
        isPurchasable: true
      }
    ]
  },
  {
    id: 102,
    name: 'هدفون بی‌سیم اپل AirPods Pro 2 Type-C',
    sku: 'APL-APP2-USBC',
    type: 'simple',
    status: 'publish',
    category: 'لوازم جانبی',
    brand: 'اپل',
    priceRange: '۱۰ تا ۱۵ میلیون',
    attributes: { 'pa_brands': 'اپل', 'pa_price-range': '۱۰ تا ۱۵ میلیون' },
    thumbnail: 'https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?w=120&auto=format&fit=crop&q=60',
    description: 'هدفون بی‌سیم اپل با تراشه H2، قابلیت حذف نویز فعال (ANC) ۲ برابر قوی‌تر و درگاه USB-C ضد گرد و غبار.',
    shortDescription: 'ایرپاد پرو ۲ با پورت تایپ سی و نویز کنسلینگ فعال',
    regularPrice: 14200000,
    salePrice: 13500000,
    manageStock: true,
    stockQuantity: 25,
    stockStatus: 'instock',
    snappayEnabled: true,
    torobPayEnabled: true,
    isPurchasable: true
  },
  {
    id: 103,
    name: 'ساعت مچی هوشمند شیائومی Watch S3',
    sku: 'XIA-WS3-SIL',
    type: 'simple',
    status: 'publish',
    category: 'ساعت و مچ‌بند',
    brand: 'شیائومی',
    priceRange: '۵ تا ۱۰ میلیون',
    attributes: { 'pa_brands': 'شیائومی', 'pa_price-range': '۵ تا ۱۰ میلیون' },
    thumbnail: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=120&auto=format&fit=crop&q=60',
    description: 'ساعت هوشمند شیائومی با فریم قابل تعویض، سیستم عامل HyperOS و باتری قدرتمند با شارژدهی ۱۵ روزه.',
    shortDescription: '',
    regularPrice: 6800000,
    salePrice: null,
    manageStock: true,
    stockQuantity: 0,
    stockStatus: 'outofstock',
    snappayEnabled: false,
    torobPayEnabled: true,
    isPurchasable: true
  },
  {
    id: 104,
    name: 'پاوربانک ۲۰۰۰۰ میلی‌آمپر باسئوس Blade 100W',
    sku: 'BSU-BLD-100W',
    type: 'simple',
    status: 'publish',
    category: 'لوازم جانبی',
    brand: 'باسئوس',
    priceRange: '۲ تا ۵ میلیون',
    attributes: { 'pa_brands': 'باسئوس', 'pa_price-range': '۲ تا ۵ میلیون' },
    thumbnail: 'https://images.unsplash.com/photo-1609592426507-42518e9d5598?w=120&auto=format&fit=crop&q=60',
    description: 'پاوربانک باریک فست شارژ با توان خروجی ۱۰۰ وات مناسب شارژ همزمان لپ‌تاپ و گوشی‌های هوشمند.',
    shortDescription: 'پاوربانک ۱۰۰ واتی با ضخامت ۱۸ میلی‌متر و نمایشگر دیجیتال',
    regularPrice: 3850000,
    salePrice: 3490000,
    manageStock: true,
    stockQuantity: 18,
    stockStatus: 'instock',
    snappayEnabled: true,
    torobPayEnabled: true,
    isPurchasable: true
  },
  {
    id: 105,
    name: 'ساعت مچی مردانه کاسیو ادیفایس Casio Edifice Chronograph',
    sku: 'CAS-EDF-550',
    type: 'simple',
    status: 'publish',
    category: 'ساعت و مچ‌بند',
    brand: 'Casio',
    priceRange: '۵ تا ۱۰ میلیون',
    attributes: { 'pa_brands': 'Casio', 'pa_price-range': '۵ تا ۱۰ میلیون' },
    thumbnail: 'https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=120&auto=format&fit=crop&q=60',
    description: 'ساعت مچی اسپرت مردانه با بند استیل ضدزنگ، کرنوگراف دقیق و ضدآب تا عمق ۱۰۰ متر.',
    shortDescription: 'کاسیو ادیفایس کرنوگراف اورجینال',
    regularPrice: 8900000,
    salePrice: 8200000,
    manageStock: true,
    stockQuantity: 12,
    stockStatus: 'instock',
    snappayEnabled: true,
    torobPayEnabled: true,
    isPurchasable: true
  },
  {
    id: 106,
    name: 'ساعت مچی کلاسیک تیسوت TISSOT PRX Powermatic 80',
    sku: 'TIS-PRX-AUTO',
    type: 'simple',
    status: 'publish',
    category: 'ساعت و مچ‌بند',
    brand: 'TISSOT',
    priceRange: '۳۰ تا ۴۰ میلیون',
    attributes: { 'pa_brands': 'TISSOT', 'pa_price-range': '۳۰ تا ۴۰ میلیون' },
    thumbnail: 'https://images.unsplash.com/photo-1547996160-71dfabb1ab2d?w=120&auto=format&fit=crop&q=60',
    description: 'ساعت اتوماتیک سوئیسی با کالیبر پاورماتیک ۸۰، شیشه یاقوت کبود ضدخش و ذخیره انرژی ۸۰ ساعت.',
    shortDescription: 'تیسوت پی‌آرایکس اتوماتیک اصل سوئیس',
    regularPrice: 38500000,
    salePrice: null,
    manageStock: true,
    stockQuantity: 4,
    stockStatus: 'instock',
    snappayEnabled: true,
    torobPayEnabled: true,
    isPurchasable: true
  },
  {
    id: 107,
    name: 'ساعت سواچ Swatch Big Bold Chrono',
    sku: 'SWA-BB-BLK',
    type: 'simple',
    status: 'publish',
    category: 'ساعت و مچ‌بند',
    brand: 'Swatch',
    priceRange: '۵ تا ۱۰ میلیون',
    attributes: { 'pa_brands': 'Swatch', 'pa_price-range': '۵ تا ۱۰ میلیون' },
    thumbnail: 'https://images.unsplash.com/photo-1533139502658-0198f920d8e8?w=120&auto=format&fit=crop&q=60',
    description: 'ساعت کژوال و مدرن سواچ با طراحی جذاب و بدنه سیلیکونی سبک و بادوام.',
    shortDescription: 'سواچ سوئیس بدنه ۴۷ میلی‌متری',
    regularPrice: 7200000,
    salePrice: 6500000,
    manageStock: true,
    stockQuantity: 9,
    stockStatus: 'instock',
    snappayEnabled: true,
    torobPayEnabled: true,
    isPurchasable: true
  },
  {
    id: 108,
    name: 'لپ‌تاپ ایسوس ROG Zephyrus G16 (2024)',
    sku: 'ASU-ROG-G16',
    type: 'variable',
    status: 'publish',
    category: 'لپ‌تاپ',
    brand: 'ایسوس',
    thumbnail: 'https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=120&auto=format&fit=crop&q=60',
    description: 'لپ‌تاپ گیمینگ فوق باریک با نمایشگر OLED ROG Nebula، پردازنده‌های نسل جدید Intel Core Ultra و گرافیک‌های سری RTX 40.',
    shortDescription: 'لپ‌تاپ گیمینگ پرچمدار با نمایشگر 2.5K OLED 240Hz',
    regularPrice: 125000000,
    salePrice: 121000000,
    manageStock: true,
    stockQuantity: 5,
    stockStatus: 'instock',
    snappayEnabled: false,
    torobPayEnabled: false,
    isPurchasable: true,
    variations: [
      {
        id: 1051,
        parentId: 105,
        sku: 'ASU-ROG-G16-RTX4070',
        name: 'پردازنده Core Ultra 9 / RTX 4070 / 32GB RAM',
        attributes: { 'کارت گرافیک': 'RTX 4070' },
        regularPrice: 125000000,
        salePrice: 121000000,
        manageStock: true,
        stockQuantity: 3,
        stockStatus: 'instock',
        snappayEnabled: false,
        torobPayEnabled: false,
        isPurchasable: true
      },
      {
        id: 1052,
        parentId: 105,
        sku: 'ASU-ROG-G16-RTX4080',
        name: 'پردازنده Core Ultra 9 / RTX 4080 / 32GB RAM',
        attributes: { 'کارت گرافیک': 'RTX 4080' },
        regularPrice: 158000000,
        salePrice: null,
        manageStock: true,
        stockQuantity: 2,
        stockStatus: 'instock',
        snappayEnabled: false,
        torobPayEnabled: false,
        isPurchasable: true
      }
    ]
  },
  {
    id: 106,
    name: 'اسپرسوساز مباشی مدل ECM2031',
    sku: 'MEB-ECM-2031',
    type: 'simple',
    status: 'draft',
    category: 'لوازم خانگی',
    brand: 'مباشی',
    thumbnail: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=120&auto=format&fit=crop&q=60',
    description: 'اسپرسوساز خانگی و نیمه‌صنعتی با فشار بخار ۲۰ بار و توان حرارتی ۱۱۰۰ وات، بدنه استیل مات ضدخش.',
    shortDescription: 'دستگاه اسپرسوساز ۲۰ بار مباشی برای قهوه و کاپوچینو',
    regularPrice: 5200000,
    salePrice: 4850000,
    manageStock: true,
    stockQuantity: 9,
    stockStatus: 'instock',
    snappayEnabled: true,
    torobPayEnabled: false,
    isPurchasable: false
  },
  {
    id: 107,
    name: 'تبلت اپل iPad Air 11-inch M2',
    sku: 'APL-IPAD-AIR-M2',
    type: 'simple',
    status: 'publish',
    category: 'تبلت',
    brand: 'اپل',
    thumbnail: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=120&auto=format&fit=crop&q=60',
    description: 'آیپد ایر ۲۰۲۴ با پردازنده فوق‌العاده سریع Apple M2، پشتیبانی از قلم Apple Pencil Pro و دوربین لندسکیپ.',
    shortDescription: 'تبلت ۱۱ اینچی اپل با پردازنده M2',
    regularPrice: 46000000,
    salePrice: null,
    manageStock: true,
    stockQuantity: 7,
    stockStatus: 'instock',
    snappayEnabled: true,
    torobPayEnabled: true,
    isPurchasable: true
  },
  {
    id: 108,
    name: 'سرخ‌کن بدون روغن فیلیپس مدل HD9200',
    sku: 'PHI-HD9200-W',
    type: 'simple',
    status: 'publish',
    category: 'لوازم خانگی',
    brand: 'فیلیپس',
    thumbnail: 'https://images.unsplash.com/photo-1586208958839-06c17cacdf08?w=120&auto=format&fit=crop&q=60',
    description: 'هواپز و سرخ‌کن رژیمی بدون روغن فیلیپس با تکنولوژی Rapid Air برای ۹۰ درصد چربی کمتر در غذا.',
    shortDescription: 'سرخ‌کن رژیمی ۴.۱ لیتری فیلیپس',
    regularPrice: 4900000,
    salePrice: 4500000,
    manageStock: false,
    stockQuantity: 0,
    stockStatus: 'instock',
    snappayEnabled: true,
    torobPayEnabled: true,
    isPurchasable: true
  }
];

export const defaultSettings: PluginSettings = {
  batchSize: 20,
  historyRetentionDays: 60,
  auditLogEnabled: true,
  rollbackEnabled: true,
  snappayMetaKey: '_snappay_eligible_product',
  snappayPluginActive: true,
  torobMetaKey: '_torob_pay_available',
  torobPluginActive: true,
  priceRoundUnit: 1000
};

export const sampleHistory: OperationLog[] = [
  {
    id: 'f47ac10b-58cc-4372-a567-0e02b2c3d479',
    userId: 1,
    userName: 'مدیر کل (admin)',
    timestamp: '۱۴۰۳/۰۷/۰۱ - ۱۱:۳۰',
    description: 'افزایش ۱۰ درصدی قیمت فروش لوازم جانبی',
    totalItems: 3,
    successCount: 3,
    failCount: 0,
    status: 'completed',
    filtersSummary: 'دسته: لوازم جانبی | وضعیت انتشار: منتشر شده',
    changesSummary: 'قیمت عادی: +۱۰٪ | گردکردن: ۱,۰۰۰ تومان',
    items: [
      {
        productId: 102,
        name: 'هدفون بی‌سیم اپل AirPods Pro 2',
        sku: 'APL-APP2-USBC',
        beforeData: { regularPrice: 12900000 },
        afterData: { regularPrice: 14200000 },
        rolledBack: false
      },
      {
        productId: 104,
        name: 'پاوربانک ۲۰۰۰۰ میلی‌آمپر باسئوس',
        sku: 'BSU-BLD-100W',
        beforeData: { regularPrice: 3500000 },
        afterData: { regularPrice: 3850000 },
        rolledBack: false
      }
    ]
  }
];
